 - name: Disable nginx enable modules and install
   hosts: 172.31.38.240
   become: true
   tasks: 

     - name: Set prompt
       ansible.builtin.shell: set-prompt frontend

     - name: Disable nginx modules first
       ansible.builtin.shell: dnf module disable nginx -y
    
     - name: Enable nginx modules
       ansible.builtin.shell: dnf module enable nginx:1.24 -y

     - name: Install nginx on frontend
       ansible.builtin.dnf:
         name: nginx
         state: installed


     - name: Recursively remove directory
       ansible.builtin.file:
         path: /usr/share/nginx/html/*
         state: absent


     - name: Copy nginx.conf file to web root
       ansible.builtin.template:
         src: nginx.conf
         dest: /etc/nginx/nginx.conf


           #   - name: Extract frontend-v3.zip into /usr/share/nginx/html
           # ansible.builtin.unarchive:
           # src: curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
           # dest: /usr/share/nginx/html
     - name: Download frontend-v3.zip
       ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
         dest: /tmp/frontend.zip

     - name: Extract frontend-v3.zip into /usr/share/nginx/html
       ansible.builtin.unarchive:
         src:  /tmp/frontend.zip
         dest: /usr/share/nginx/html
         remote_src: yes      # remote_src: yes  
   

     - name: Start the service
       ansible.builtin.service:
         name: nginx
         state: started
         enabled: yes
