default:
    @git pull & > /dev/null
    echo ansible-playbook -i $(app_name)-$(env).chatgpt1.info, -e ansible_user=ec2-user -e ansible_password=DevOps321 -e env=$(env) -e app_name=$(app_name) roboshop.yml








#to run the make file 
# app_name=redis env=dev make
#app_name=user env=dev make



