     - name: Set prompt
       ansible.builtin.shell: set-prompt {{ app-name}}- {{ env }}

     - name: Load NodeJS
       ansible.builtin.include_role:
         name: common
         tasks_from: nodejs
    
     - name: Copy mongo.repo file to repo root
       ansible.builtin.template:
         src: mongo.repo
         dest: /etc/yum.repos.d/mongo.repo

         
     - name: Install mongodb-mongosh
       ansible.builtin.dnf: 
         name: mongodb-mongosh
         state: installed   


     - name: Reload service daemon-reload, in all cases
       ansible.builtin.command: systemctl daemon-reload
         
   
     - name: Load Master Data 
       ansible.builtin.shell: mongosh --host mongodb-{{ app-name }}.devopspractice.info </app/db/master-data.js

     - name: Start the service
       ansible.builtin.systemd_service:
         name: catalogue.service
         state: restarted
         enabled: yes
