 - name: Disable nginx -enable modules and install
   hosts: frontend
   become: true
   tasks: 
     - name: Disable nginx modules first
       ansible.builtin.dnf: dnf module disable nginx -y
    
     - name: Enable nginx modules
       ansible.builtin.dnf: dnf module enable nginx:1.24 -y

     - name: Install nginx on frontend
       ansible.builtin.dnf:
         name: nginx
         state: installed


     - name: Recursively remove directory
       ansible.builtin.file:
         path: /usr/share/nginx/html/*
         state: absent


     - name: Copy nginx.conf file to web root
       ansible.builtin.template:
         src: nginx.conf
         dest: /usr/share/nginx/html

     - name: Extract frontend-v3.zip into /usr/share/nginx/html
       ansible.builtin.unarchive:
         src: curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
         dest: /usr/share/nginx/html
   
     - name: Start the service
       ansible.builtin.service:
         name: nginx
         state: started
         enabled: yes