#dnf install python3 gcc python3-devel -y
#useradd roboshop
#mkdir /app 
#curl -L -o /tmp/payment.zip https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
#cd /app 
#unzip /tmp/payment.zip
#cd /app 
#pip3 install -r requirements.txt
#/etc/systemd/system/payment.service
#systemctl daemon-reload
#systemctl enable payment 
#systemctl start payment
 - name: Setup Payment host
   hosts: payment
   become: true
   tasks:
     - name: Install Python and required components
       ansible.builtin.dnf:
         name: "{{ item }}"
         state: installed       
       loop:
         - python3
         - gcc
         - python3-devel
      
     - name: Create a user 'roboshop' with a home directory
       ansible.builtin.user:
         name: roboshop
      
     - name: Create a directory if it does not exist
       ansible.builtin.file:
         path: /app 
         state: directory

    
     - name: Copy payment.service file to /etc/systemd/system/
       ansible.builtin.template:
         src: payment.service
         dest: /etc/systemd/system/payment.service

     - name: Extract frontend-v3.zip into /usr/share/nginx/html
       ansible.builtin.unarchive:
         src: curl -L -o /tmp/payment.zip https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
         dest: /app

     - name: Install requirements on payment host
       ansible.builtin.shell: pip3 install -r requirements.txt
 
          
     - name: Reload service daemon-reload, in all cases
       ansible.builtin.systemd_service:
         name: daemon-reload
         state: reloaded   
   
     - name: Start the service
       ansible.builtin.systemd_service:
         name: payment.service
         state: started
         enabled: yes         
