- name: Setup Rabbitmq host
  hosts: rabbitmq
  become: true
  tasks: 
    - name: Install rabbitmq-server on host
      ansible.builtin.dnf: 
        name: rabbitmq-server
        state: installed

    - name: Enable and start the rabbitmq service
      ansible.builtin.systemd_service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Create one user for the application.
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123
     
    - name: Set permission to roboshop user
      ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

 
        
    - name: Enable and start the rabbitmq service
      ansible.builtin.systemd_service:
        name: rabbitmq-server
        state: status
