    - name: Install golang
      ansible.builtin.dnf:
        name: golang
        state: installed

    - name: Install golang requirements on dispatch host
      ansible.builtin.pip:
        requirements: app_prerequisites.yml
    
      
